name: MagicWarsManager
main: net.magicwars.manager.MagicWarsManager
version: 0.1
api-version: 1.14
depend:
commands:
   manager:
      description: Commandes admin
      usage: /manager
   mkit:
      description: Distribue un kit a un joueur
      usage: /mkit <kit> <username>